"$schema" = 'https://starship.rs/config-schema.json'

format = """
$os\
$username\
[î‚°](bg:bg_statusline4 fg:yellow)\
$directory\
[î‚°](fg:bg_statusline4 bg:bg_statusline3)\
$git_branch\
$git_status\
[î‚°](fg:bg_statusline3 bg:bg_statusline1)\
$c\
$rust\
$golang\
$nodejs\
$php\
$java\
$kotlin\
$haskell\
$python\
[î‚°](fg:bg_statusline1 bg:bg_statusline3)\
[î‚°](fg:bg_statusline3 bg:bg_statusline1)\
$time\
[î‚° ](fg:bg_statusline1)\
$line_break$character"""

palette = 'gruvbox_material'

[palettes.gruvbox_material]
yellow = '#e9b143'
fg0 = '#e2cca9'
fg1 = '#ddc7a1'
bg0 = '#282828'
bg_statusline1 = '#32302f'
bg_statusline2 = '#7c6f64'
bg_statusline3 = '#504945'
bg_statusline4 = '#a89984'
blue = '#458588'
aqua = '#689d6a'

[os]
disabled = false
style = "bg:yellow fg:bg0"

[os.symbols]
Windows = "ó°²"
Ubuntu = "ó°•ˆ"
SUSE = "ïŒ”"
Raspbian = "ó°¿"
Mint = "ó°£­"
Macos = "ó°€µ"
Manjaro = "ïŒ’"
Linux = "ó°Œ½"
Gentoo = "ó°£¨"
Fedora = "ó°£›"
Alpine = "ïŒ€"
Amazon = "ï‰°"
Android = "îœ"
Arch = "ó°£‡"
Artix = "ó°£‡"
EndeavourOS = "ï†—"
CentOS = "ïŒ„"
Debian = "ó°£š"
Redhat = "ó±„›"
RedHatEnterprise = "ó±„›"
Pop = "ïŒª"

[username]
show_always = true
style_user = "bg:yellow fg:bg0"
style_root = "bg:yellow fg:bg0"
format = '[ $user ]($style)'

[directory]
style = "fg:bg0 bg:bg_statusline4"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "â€¦/"

[directory.substitutions]
"Documents" = "ó°ˆ™ "
"Downloads" = "ï€™ "
"Music" = "ó°š "
"Pictures" = "ï€¾ "
"Developer" = "ó°²‹ "

[git_branch]
symbol = "ï˜"
style = "bg:bg_statusline3"
format = '[[ $symbol $branch ](fg:fg0 bg:bg_statusline3)]($style)'

[git_status]
style = "bg:bg_statusline3"
format = '[[($all_status$ahead_behind )](fg:fg0 bg:bg_statusline3)]($style)'

[nodejs]
symbol = "îœ˜"
style = "bg:bg_statusline1"
format = '[[ $symbol( $version) ](fg:fg0 bg:bg_statusline1)]($style)'

[c]
symbol = "î˜ "
style = "bg:bg_statusline1"
format = '[[ $symbol( $version) ](fg:fg0 bg:bg_statusline1)]($style)'

[rust]
symbol = "î¨"
style = "bg:bg_statusline1"
format = '[[ $symbol( $version) ](fg:fg0 bg:bg_statusline1)]($style)'

[golang]
symbol = "î˜§"
style = "bg:bg_statusline1"
format = '[[ $symbol( $version) ](fg:fg0 bg:bg_statusline1)]($style)'

[php]
symbol = "î˜ˆ"
style = "bg:bg_statusline1"
format = '[[ $symbol( $version) ](fg:fg0 bg:bg_statusline1)]($style)'

[java]
symbol = "î‰–"
style = "bg:bg_statusline1"
format = '[[ $symbol( $version) ](fg:fg0 bg:bg_statusline1)]($style)'

[kotlin]
symbol = "î˜´"
style = "bg:bg_statusline1"
format = '[[ $symbol( $version) ](fg:fg0 bg:bg_statusline1)]($style)'

[haskell]
symbol = "î˜Ÿ"
style = "bg:bg_statusline1"
format = '[[ $symbol( $version) ](fg:fg0 bg:bg_statusline1)]($style)'

[python]
symbol = "î˜†"
style = "bg:bg_statusline1"
format = '[[ $symbol ($virtualenv) ${version} ](fg:fg0 bg:bg_statusline1)]($style)'

[docker_context]
symbol = "ïŒˆ"
style = "bg:bg_statusline3"
format = '[[ $symbol( $context) ](fg:fg0 bg:bg_statusline3)]($style)'

[conda]
style = "bg:bg_statusline3"
format = '[[ $symbol( $environment) ](fg:fg0 bg:bg_statusline3)]($style)'

[time]
disabled = false
time_format = "%H:%M"
style = "bg:bg_statusline3"
format = '[[ $time ](fg:fg0 bg:bg_statusline1)]($style)'

[line_break]
disabled = true

[character]
disabled = false
success_symbol = '[ğŸ ¶](bold fg:aqua)'
error_symbol = '[ğŸ ¶](bold fg:red)'
vimcmd_symbol = '[ğŸ ´](bold:aqua)'
vimcmd_replace_one_symbol = '[ğŸ ´](bold:yellow)'
vimcmd_replace_symbol = '[ğŸ ´](bold:yellow)'
vimcmd_visual_symbol = '[ğŸ ´](bold:yellow)'

